

pipeline {
  agent { 
    dockerfile {
      filename 'Dockerfile'
      dir 'jenkins/jenkins-agent'
      args '-v /certs/client:/certs/client -n jenkins'
    }
   }
  stages {
    stage('Test') {
      steps {
        sh '''
          node --version
          git --version
          curl --version
        '''
      }
    }
  }
}