

pipeline {
  agent { 
    dockerfile {
      filename 'jenkins/jenkins-agent/Dockerfile'
    }
   }
  stages {
    stage('Test') {
      steps {
        sh '''
          node --version
          git --version
          curl --version
        '''
      }
    }
  }
}