version: '3.8'
networks:
  jenkinscasc-network:
    name: jenkinscasc
volumes:
  data:
    name: jenkinscasc-data
  certs:
    name: jenkinscasc-docker-certs
services:
  dind:
    container_name: jenkinscasc-docker
    image: docker:dind
    privileged: true
    restart: unless-stopped
    networks:
      jenkinscasc-network:
        aliases:
          - docker
    volumes:
      - data:/var/jenkinscasc_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      
  jenkinscasc:
    build: .
    container_name: jenkinscasc
    restart: unless-stopped
    networks:
      - jenkinscasc-network
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - data:/var/jenkinscasc_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1