unclassified:
  location:
    url: http://localhost:8080/
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy


jobs:
  - script: >
      job('example') {
       steps {
         shell('echo Hello World!')
       }
      }
  - script: >
      job('Terraform Verify') {
       steps {
         shell('terraform -version')
       }
      }
  - script: >
      pipelineJob('Toolchain') {

        def repo = 'https://github.com/ppalit/devops_toolchain.git'

        triggers {
          scm('H/5 * * * *')
        }
        description("Pipeline for $repo")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches('main')
                scriptPath('jenkins/jenkins-agent/Jenkinsfile')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }
            }
          }
        }
      }
  - script: >
      pipelineJob('docker agent') {

        def repo = 'https://github.com/darinpope/jenkins-example-docker.git'

        description("Pipeline for $repo")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches('main')
                scriptPath('Jenkinsfile-3')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }
            }
          }
        }
      }
