---
version: '3.8'

services:
  docker:
    image: alpine/socat
    container_name: socat
    ports:
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs/client
    command: "tcp-listen:2376,fork,reuseaddr unix-connect:/var/run/docker.sock"
    privileged: true

  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    depends_on:
      - docker
    networks:
      - jenkins
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
      JENKINS_ADMIN_PASSWORD: adminn
      JENKINS_SSH_GIT_KEY: "$(cat ~/.ssh/id_rsa)"
      JENKINS_JOB_DSL_URL: "git@github.com:ppalit/devops_toolchain.git"
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs
networks:
  jenkins:
